version: '3.7'
services:

  srv:
    image: aarongrisez/bellgame2-srv:release-v1.0.0
    user: node
    environment:
      - NODE_ENV=production
    command: "npm start"
    networks:
      - proxy-net
    labels:
      - "traefik.http.routers.srv.rule=Host(`localhost`) && PathPrefix(`/srv`)"
      - "traefik.http.middlewares.srv-stripprefix.stripprefix.prefixes=/srv"
      - "traefik.http.middlewares.srv-stripprefix.stripprefix.forceslash=false"
      - "traefik.http.routers.srv.entrypoints=web"
      - "traefik.http.routers.srv.middlewares=srv-stripprefix"

  app:
    image: aarongrisez/bellgame2-app:release-v1.0.0
    networks:
      - proxy-net
    labels:
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
  
networks:
  proxy-net:
    external: true