version: '3.7'
services:

  app:
    build:
      dockerfile: ./dev.Dockerfile
      context: .
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - ./package.json:/usr/src/app/package.json
      - ./yarn.lock:/usr/src/app/yarn.lock
    environment:
      - NODE_ENV=development
      - SKIP_PREFLIGHT_CHECK=true
      - REACT_APP_AUTH0_DOMAIN=dev-k1aifjsj.auth0.com
      - REACT_APP_AUTH0_CLIENT_ID=7fLB8KTeluEZVjRA9s0BhOBzmDl38ImE
      - REACT_APP_AUTH0_AUDIENCE=https://bellga.me/srv
      - REACT_APP_GAME_SERVER=http://localhost:8080/srv
    ports:
      - 3000:3000