version: '3'
services:

  srv:
    build:
      context: ./srv
    volumes:
      - ./srv/src:/home/node/app/src
      - ./bellgame:/home/node/app/bellgame
    user: node
    working_dir: /home/node/app/src
    environment:
      - NODE_ENV=development
    ports:
      - 8000:8000
    command: "npm start"
    depends_on: 
      - mongo
  
  app:
    build:
      context: ./app
    volumes:
      - ./app/src:/home/node/app/src
      - ./bellgame:/home/node/app/bellgame
    working_dir: /home/node/app/src
    environment:
      - NODE_ENV=development
    ports:
      - 80:3000
    command: "npm start"
    depends_on: 
      - mongo

  
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
