version: '3'
services:

  srv:
    image: registry.gitlab.com/aarongrisez/bellgame2/srv:latest
    user: node
    working_dir: /home/node/app/src
    environment:
      - NODE_ENV=production
    command: "npm start"
    depends_on: 
      - mongo
  
  app:
    image: registry.gitlab.com/aarongrisez/bellgame2/app:latest
    working_dir: /app/src
    environment:
      - NODE_ENV=production
    command: "npm start"
    depends_on: 
      - mongo

  traefik:
    image: "traefik:v2.0.0-rc3"
    container_name: "traefik"
    command:
      - "--log.level=INFO"
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"