version: '3'
services:

  srv:
    build:
      context: .
      dockerfile: srv/Dockerfile
    volumes:
      - ./:/home/node/app
    user: node
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - "8000:8000"
    command: "npm run server"