version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          docker build -t aarongrisez/bellgame2-app:<<pipeline.git.revision>> . |
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin |
          docker push aarongrisez/bellgame2-app:<<pipeline.git.revision>>  