version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/project
    steps:
      - checkout
      - run: |
          cd app
          docker build -t aarongrisez/bellgame2-app:<< pipeline.git.revision >>dev --dockerfile dev.Dockerfile .
          echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
          docker push aarongrisez/bellgame2-app:<< pipeline.git.revision >>dev 